# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    redirectionListener : 
         class : Ecommerce\EcommerceBundle\Listener\RedirectionListener
         arguments : [ '@service_container','@session', '@security.token_storage' ]
         tags : 
         - { name : 'kernel.event_listener', event :  'kernel.request', method : 'onKernelRequest' }