<?php

namespace Page\PageBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
  public function getAllFaqs()
  {
    $qb = $this->createQueryBuilder('u')
    ->select('u')
    ->where('u.titre like  :u1')
    ->orWhere('u.titre like  :u2')
    ->setParameter('u1', "Mentions%")
    ->setParameter('u2', "Qui%");

    return $qb->getQuery()->getResult();
  }

  public function getFaq($id)
  {
    $qb = $this->createQueryBuilder('u')
    ->select('u')
    ->where('u.id = :uid')
    ->setParameter('uid', $id);

    return $qb->getQuery()->getOneOrNullResult();
  }
}
