<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
	public function byCategorie($categorie){
	$qb = $this->createQueryBuilder('u')
	->select('u')
	->where('u.category = :category')
	->orderBy('u.id')
	->setParameter('category', $categorie);
	 return $qb->getQuery()->getResult();

	}
	public function recherche($chaine){
		$qb = $this->createQueryBuilder('u')
		->select('u')
		->where('u.nom LIKE :chaine')
		->orWhere('u.description LIKE :chaine')
		->orderBy('u.id')
		->setParameter('chaine', $chaine);
		return $qb->getQuery()->getResult();
	}
	public function findArray($array){
		$qb = $this->createQueryBuilder('u')
		->select('u')
		->where('u.id IN  (:array)')
		->orderBy('u.id', 'DESC')
		->setParameter('array', $array);
		return $qb->getQuery()->getResult();
	}

}
